name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Postgresql with Postgis and Custom Port
      uses: ./
      with:
        postgresql user: 'test'
        postgresql password: ${{ secrets.DatabasePassword }}
        postgresql db: 'test-custom'
        postgresql port: '6543'

    - name: Set up Postgresql with Postgis and Default Port
      uses: ./
      with:
        postgresql user: 'test'
        postgresql password: ${{ secrets.DatabasePassword }}
        postgresql db: 'test-default'

    - name: ACTIONS_ALLOW_UNSECURE_COMMANDS
      run: echo 'ACTIONS_ALLOW_UNSECURE_COMMANDS=true' >> $GITHUB_ENV

    - uses: jiro4989/setup-nim-action@v1.0.1

    - name: Run custom port test
      run: nim c -r tests/customPortConnection.nim
      env:
        password: ${{ secrets.DatabasePassword }}

    - name: Run default port test
      run: nim c -r tests/defaultPortConnection.nim