name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Postgresql with Postgis
      uses: aryeohq/postgis-action@${{ github.ref_name }}
      with:
        postgresql user: 'test'
        postgresql password: ${{ secrets.DatabasePassword }}
        postgresql db: 'test'
        postgresql port: '6543'

    - name: ACTIONS_ALLOW_UNSECURE_COMMANDS
      run: echo 'ACTIONS_ALLOW_UNSECURE_COMMANDS=true' >> $GITHUB_ENV

    - uses: jiro4989/setup-nim-action@v1.0.1

    - name: Run test
      run: nim c -r tests/connection.nim
      env:
        password: ${{ secrets.DatabasePassword }}